Refacto/templates
Mak-API/website pull request #114
Opened 2019-03-05 21:32 UTC by Backins

2019-03-07 13:06 UTC, ivanPrunier approved these changes

2019-03-07 17:20 UTC, mehdou92 commented on templates/Front/User/show.html.twig
> +    {#
Delete comment here

2019-03-07 17:21 UTC, mehdou92 requested changes
Request for the commented code :)

2019-03-07 22:10 UTC, Backins commented on templates/Front/User/show.html.twig
> +    {#
Resolve

2019-03-08 09:10 UTC, mehdou92 approved these changes

2019-03-08 09:10 UTC, merged